# Generated by Django 5.2.6 on 2025-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('imo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('mmsi', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('length_m', models.IntegerField(blank=True, null=True)),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
