# Generated by Django 5.2.6 on 2025-10-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={},
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='mmsi',
            new_name='MMSI',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='draft_m',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='name',
            new_name='shipName',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='imo',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='length_m',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='type',
        ),
        migrations.AddField(
            model_name='ship',
            name='beam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='callSign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='cargoType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ship',
            name='grossTonnage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ship',
            name='priorityLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ship',
            name='shipId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ship',
            name='shipType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
