# Generated by Django 5.2.6 on 2025-09-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField()),
                ('etd', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('alongside', 'Alongside'), ('departed', 'Departed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='planned', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('cargo_desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_calls', to='ships.ship')),
            ],
            options={
                'ordering': ['eta'],
            },
        ),
        migrations.CreateModel(
            name='BerthAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ports.berth')),
                ('port_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.portcall')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
