# Generated by Django 5.2.6 on 2025-10-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('ports', '0002_port_alter_berth_options_and_more'),
        ('ships', '0002_alter_ship_options_rename_mmsi_ship_mmsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.BigAutoField(primary_key=True, serialize=False)),
                ('destinationPort', models.CharField(blank=True, max_length=200)),
                ('ETA', models.DateTimeField(blank=True, null=True)),
                ('ATA', models.DateTimeField(blank=True, null=True)),
                ('ETD', models.DateTimeField(blank=True, null=True)),
                ('ATD', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ETA'],
            },
        ),
        migrations.RemoveField(
            model_name='portcall',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='berthassignment',
            name='port_call',
        ),
        migrations.AlterModelOptions(
            name='berthassignment',
            options={'ordering': ['ETA']},
        ),
        migrations.RenameField(
            model_name='berthassignment',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='berthassignment',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='berthassignment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='berthassignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='berthassignment',
            name='start',
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='ATA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='ATD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='ETA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='ETD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='assignedBy',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='assignmentId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='berthassignment',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ships.ship'),
        ),
        migrations.AlterField(
            model_name='berthassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='berthassignment',
            index=models.Index(fields=['berth', 'ETA', 'ETD'], name='operations__berth_i_a833b2_idx'),
        ),
        migrations.AddIndex(
            model_name='berthassignment',
            index=models.Index(fields=['ship', 'status'], name='operations__ship_id_a27365_idx'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='berth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='ports.berth'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ships.ship'),
        ),
        migrations.DeleteModel(
            name='PortCall',
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['ship', 'ETA', 'ETD'], name='operations__ship_id_74bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['berth', 'ETA', 'ETD'], name='operations__berth_i_00af0c_idx'),
        ),
    ]
