# Generated by Django 5.2.6 on 2025-10-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0002_port_alter_berth_options_and_more'),
        ('ships', '0002_alter_ship_options_rename_mmsi_ship_mmsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngine',
            fields=[
                ('aiEngineId', models.BigAutoField(primary_key=True, serialize=False)),
                ('modelType', models.CharField(max_length=100)),
                ('trainingData', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('dataId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ETA', models.DateTimeField(blank=True, null=True)),
                ('ATA', models.DateTimeField(blank=True, null=True)),
                ('ETD', models.DateTimeField(blank=True, null=True)),
                ('ATD', models.DateTimeField(blank=True, null=True)),
                ('congestionLevel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utilizationRate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='ports.berth')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='ships.ship')),
            ],
            options={
                'indexes': [models.Index(fields=['ship', 'berth', 'ETA', 'ETD'], name='analytics_h_ship_id_3c4cc5_idx')],
            },
        ),
    ]
