# Generated by Django 5.2.6 on 2025-10-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('portId', models.BigAutoField(primary_key=True, serialize=False)),
                ('portName', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('totalBerths', models.IntegerField(default=0)),
                ('totalShips', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='berth',
            options={},
        ),
        migrations.RenameField(
            model_name='berth',
            old_name='length_m',
            new_name='craneCount',
        ),
        migrations.RenameField(
            model_name='berth',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='berth',
            old_name='max_draft_m',
            new_name='maxDraft',
        ),
        migrations.RenameField(
            model_name='berth',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='berth',
            name='availabilityStatus',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], default='available', max_length=20),
        ),
                migrations.RemoveField(
            model_name='berth',
            name='id',
        ),

        migrations.AddField(
            model_name='berth',
            name='berthId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='berth',
            name='berthName',
            field=models.CharField(blank=True, default='Berth', max_length=100),
        ),
        migrations.AddField(
            model_name='berth',
            name='craneCapacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='loadingRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='maxShipCapacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='preferredShipType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='berth',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='port',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='berths',
                to='ports.port',
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='berth',
            unique_together={('port', 'berthName')},
        ),
        migrations.AddIndex(
            model_name='berth',
            index=models.Index(fields=['port', 'berthName'], name='ports_berth_port_id_ef1943_idx'),
        ),
        migrations.RemoveField(
            model_name='berth',
            name='name',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='status',
        ),
    ]
