# Generated by Django 5.2.6 on 2025-10-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_port_alter_berth_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='ports.port'),
        ),
    ]
