# Generated by Django 5.2.6 on 2025-10-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0002_port_alter_berth_options_and_more'),
        ('ships', '0002_alter_ship_options_rename_mmsi_ship_mmsi_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOverrideLogs',
            fields=[
                ('logId', models.BigAutoField(primary_key=True, serialize=False)),
                ('overrideReason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='ports.berth')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='ships.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='users.user')),
            ],
        ),
    ]
